#! /usr/bin/env bash

tmux new-session -d -s main
tmux split-window -h
tmux select-pane -t main:1.2
tmux resize-pane -x 80
tmux select-pane -t main:1.1
tmux split-window -v
tmux select-pane -t main:1.3
tmux split-window -v
tmux new-window
tmux split-window -h
tmux select-pane -t main:2.2
tmux resize-pane -x 80
tmux split-window -v

tmux send-keys -t main:1.1 'htop' C-m
tmux send-keys -t main:1.2 'cmus' C-m

tmux select-window -t main:1
tmux select-pane -t main:1.3
tmux -2 attach-session -t main
